from api import Item

items = [Item(name='item_branches', localized_name='Iron Branch', cost=50, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_quelling_blade', localized_name='Quelling Blade', cost=100, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_stout_shield', localized_name='Stout Shield', cost=100, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_orb_of_corrosion', localized_name='Рецепт: Orb of Corrosion', cost=100, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_gauntlets', localized_name='Gauntlets of Strength', cost=140, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_slippers', localized_name='Slippers of Agility', cost=140, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_mantle', localized_name='Mantle of Intelligence', cost=140, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_magic_wand', localized_name='Рецепт: Magic Wand', cost=150, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_ironwood_tree', localized_name='Ironwood Tree', cost=151, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_circlet', localized_name='Circlet', cost=155, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_ring_of_protection', localized_name='Ring of Protection', cost=175, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_ring_of_regen', localized_name='Ring of Regen', cost=175, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_sobi_mask', localized_name="Sage's Mask", cost=175, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_magic_stick', localized_name='Magic Stick', cost=200, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_heavens_halberd', localized_name="Рецепт: Heaven's Halberd", cost=200, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_bracer', localized_name='Рецепт: Bracer', cost=210, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_wraith_band', localized_name='Рецепт: Wraith Band', cost=210, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_null_talisman', localized_name='Рецепт: Null Talisman', cost=210, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_soul_ring', localized_name='Рецепт: Soul Ring', cost=245, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_wind_lace', localized_name='Wind Lace', cost=250, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_fluffy_hat', localized_name='Fluffy Hat', cost=250, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_buckler', localized_name='Рецепт: Buckler', cost=250, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_ring_of_basilius', localized_name='Рецепт: Ring of Basilius', cost=250, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_headdress', localized_name='Рецепт: Headdress', cost=250, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_meteor_hammer', localized_name='Рецепт: Meteor Hammer', cost=250, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_falcon_blade', localized_name='Рецепт: Falcon Blade', cost=250, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_orb_of_venom', localized_name='Orb of Venom', cost=275, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_orchid', localized_name='Рецепт: Orchid Malevolence', cost=300, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_blight_stone', localized_name='Blight Stone', cost=300, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_urn_of_shadows', localized_name='Рецепт: Urn of Shadows', cost=335, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_hurricane_pike', localized_name='Рецепт: Hurricane Pike', cost=350, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_vladmir', localized_name="Рецепт: Vladmir's Offering", cost=400, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_wraith_pact', localized_name='Рецепт: Wraith Pact', cost=400, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_mage_slayer', localized_name='Рецепт: Mage Slayer', cost=400, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_buckler', localized_name='Buckler', cost=425, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_ring_of_basilius', localized_name='Ring of Basilius', cost=425, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_headdress', localized_name='Headdress', cost=425, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_blades_of_attack', localized_name='Blades of Attack', cost=450, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_belt_of_strength', localized_name='Belt of Strength', cost=450, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_boots_of_elves', localized_name='Band of Elvenskin', cost=450, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_robe', localized_name='Robe of the Magi', cost=450, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_crown', localized_name='Crown', cost=450, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_gloves', localized_name='Gloves of Haste', cost=450, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_magic_wand', localized_name='Magic Wand', cost=450, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_glimmer_cape', localized_name='Рецепт: Glimmer Cape', cost=450, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_holy_locket', localized_name='Рецепт: Holy Locket', cost=475, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_boots', localized_name='Boots of Speed', cost=500, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_cloak', localized_name='Cloak', cost=500, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_manta', localized_name='Рецепт: Manta Style', cost=500, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_lesser_crit', localized_name='Рецепт: Crystalys', cost=500, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_silver_edge', localized_name='Рецепт: Silver Edge', cost=500, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_bracer', localized_name='Bracer', cost=505, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_wraith_band', localized_name='Wraith Band', cost=505, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_null_talisman', localized_name='Null Talisman', cost=505, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_chainmail', localized_name='Chainmail', cost=550, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_blade_mail', localized_name='Рецепт: Blade Mail', cost=550, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_ancient_janggo', localized_name='Рецепт: Drum of Endurance', cost=550, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_witch_blade', localized_name='Рецепт: Witch Blade', cost=600, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_kaya', localized_name='Рецепт: Kaya', cost=600, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_sange', localized_name='Рецепт: Sange', cost=600, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_yasha', localized_name='Рецепт: Yasha', cost=600, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_armlet', localized_name='Рецепт: Armlet of Mordiggian', cost=625, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_ring_of_tarrasque', localized_name='Ring of Tarrasque', cost=650, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_cyclone', localized_name="Рецепт: Eul's Scepter of Divinity", cost=650, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_aether_lens', localized_name='Рецепт: Aether Lens', cost=650, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_shivas_guard', localized_name="Рецепт: Shiva's Guard", cost=650, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_veil_of_discord', localized_name='Рецепт: Veil of Discord', cost=650, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_monkey_king_bar', localized_name='Рецепт: Monkey King Bar', cost=675, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_voodoo_mask', localized_name='Voodoo Mask', cost=700, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_gungir', localized_name='Рецепт: Gleipnir', cost=700, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_soul_ring', localized_name='Soul Ring', cost=700, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_energy_booster', localized_name='Energy Booster', cost=800, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_crimson_guard', localized_name='Рецепт: Crimson Guard', cost=800, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_revenants_brooch', localized_name="Рецепт: Revenant's Brooch", cost=800, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_ring_of_health', localized_name='Ring of Health', cost=825, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_void_stone', localized_name='Void Stone', cost=825, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_recipe_basher', localized_name='Рецепт: Skull Basher', cost=825, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_urn_of_shadows', localized_name='Urn of Shadows', cost=840, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_rod_of_atos', localized_name='Рецепт: Rod of Atos', cost=850, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_quarterstaff', localized_name='Quarterstaff', cost=875, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_lifesteal', localized_name='Morbid Mask', cost=900, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_mekansm', localized_name='Рецепт: Mekansm', cost=900, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_bloodstone', localized_name='Рецепт: Bloodstone', cost=900, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_sphere', localized_name="Рецепт: Linken's Sphere", cost=900, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_mjollnir', localized_name='Рецепт: Mjollnir', cost=900, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_solar_crest', localized_name='Рецепт: Solar Crest', cost=900, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_bloodthorn', localized_name='Рецепт: Bloodthorn', cost=925, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_orb_of_corrosion', localized_name='Orb of Corrosion', cost=925, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_tranquil_boots', localized_name='Tranquil Boots', cost=925, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_force_staff', localized_name='Рецепт: Force Staff', cost=950, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_helm_of_iron_will', localized_name='Helm of Iron Will', cost=975, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_helm_of_the_dominator', localized_name='Рецепт: Helm of the Dominator', cost=975,
              secret_shop=0, recipe=1, parent_name=[]),
         Item(name='item_broadsword', localized_name='Broadsword', cost=1000, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_ogre_axe', localized_name='Ogre Axe', cost=1000, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_blade_of_alacrity', localized_name='Blade of Alacrity', cost=1000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_staff_of_wizardry', localized_name='Staff of Wizardry', cost=1000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_blitz_knuckles', localized_name='Blitz Knuckles', cost=1000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_vitality_booster', localized_name='Vitality Booster', cost=1000, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_spirit_vessel', localized_name='Рецепт: Spirit Vessel', cost=1000, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_greater_crit', localized_name='Рецепт: Daedalus', cost=1000, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_shadow_amulet', localized_name='Shadow Amulet', cost=1000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_medallion_of_courage', localized_name='Medallion of Courage', cost=1025, secret_shop=0,
              recipe=0, parent_name=[]),
         Item(name='item_recipe_diffusal_blade', localized_name='Рецепт: Diffusal Blade', cost=1050, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_javelin', localized_name='Javelin', cost=1100, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_eternal_shroud', localized_name='Рецепт: Eternal Shroud', cost=1100, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_ethereal_blade', localized_name='Рецепт: Ethereal Blade', cost=1100, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_falcon_blade', localized_name='Falcon Blade', cost=1125, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_point_booster', localized_name='Point Booster', cost=1200, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_heart', localized_name='Рецепт: Heart of Tarrasque', cost=1200, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_aeon_disk', localized_name='Рецепт: Aeon Disk', cost=1200, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_dagon', localized_name='Рецепт: Dagon', cost=1250, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_talisman_of_evasion', localized_name='Talisman of Evasion', cost=1300, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_wind_waker', localized_name='Рецепт: Wind Waker', cost=1300, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_assault', localized_name='Рецепт: Assault Cuirass', cost=1300, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_arcane_boots', localized_name='Arcane Boots', cost=1300, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_helm_of_the_overlord', localized_name='Рецепт: Helm of the Overlord', cost=1325,
              secret_shop=0, recipe=1, parent_name=[]),
         Item(name='item_claymore', localized_name='Claymore', cost=1350, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_platemail', localized_name='Platemail', cost=1400, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_power_treads', localized_name='Power Treads', cost=1400, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_black_king_bar', localized_name='Рецепт: Black King Bar', cost=1450, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_ghost', localized_name='Ghost Scepter', cost=1500, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_phase_boots', localized_name='Phase Boots', cost=1500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_oblivion_staff', localized_name='Oblivion Staff', cost=1500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_hood_of_defiance', localized_name='Hood of Defiance', cost=1500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_boots_of_bearing', localized_name='Рецепт: Boots of Bearing', cost=1500, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_guardian_greaves', localized_name='Рецепт: Guardian Greaves', cost=1500, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_veil_of_discord', localized_name='Veil of Discord', cost=1525, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_pipe', localized_name='Рецепт: Pipe of Insight', cost=1550, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_abyssal_blade', localized_name='Рецепт: Abyssal Blade', cost=1550, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_mithril_hammer', localized_name='Mithril Hammer', cost=1600, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_pers', localized_name='Perseverance', cost=1650, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_recipe_refresher', localized_name='Рецепт: Refresher Orb', cost=1700, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_ancient_janggo', localized_name='Drum of Endurance', cost=1700, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_arcane_blink', localized_name='Рецепт: Arcane Blink', cost=1750, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_recipe_swift_blink', localized_name='Рецепт: Swift Blink', cost=1750, secret_shop=0, recipe=1,
              parent_name=[]),
         Item(name='item_recipe_overwhelming_blink', localized_name='Рецепт: Overwhelming Blink', cost=1750,
              secret_shop=0, recipe=1, parent_name=[]),
         Item(name='item_recipe_hand_of_midas', localized_name='Рецепт: Hand of Midas', cost=1750, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_mask_of_madness', localized_name='Mask of Madness', cost=1775, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_vanguard', localized_name='Vanguard', cost=1825, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_mekansm', localized_name='Mekansm', cost=1875, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_dragon_lance', localized_name='Dragon Lance', cost=1900, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_lesser_crit', localized_name='Crystalys', cost=1950, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_glimmer_cape', localized_name='Glimmer Cape', cost=1950, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_recipe_travel_boots', localized_name='Рецепт: Boots of Travel', cost=2000, secret_shop=0,
              recipe=1, parent_name=[]),
         Item(name='item_hyperstone', localized_name='Hyperstone', cost=2000, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_ultimate_orb', localized_name='Ultimate Orb', cost=2050, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_kaya', localized_name='Kaya', cost=2050, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_sange', localized_name='Sange', cost=2050, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_yasha', localized_name='Yasha', cost=2050, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_blade_mail', localized_name='Blade Mail', cost=2100, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_demon_edge', localized_name='Demon Edge', cost=2200, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_hand_of_midas', localized_name='Hand of Midas', cost=2200, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_force_staff', localized_name='Force Staff', cost=2200, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_blink', localized_name='Blink Dagger', cost=2250, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_aether_lens', localized_name='Aether Lens', cost=2275, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_meteor_hammer', localized_name='Meteor Hammer', cost=2350, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_holy_locket', localized_name='Holy Locket', cost=2400, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_helm_of_the_dominator', localized_name='Helm of the Dominator', cost=2400, secret_shop=0,
              recipe=0, parent_name=[]),
         Item(name='item_mage_slayer', localized_name='Mage Slayer', cost=2400, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_travel_boots', localized_name='Boots of Travel', cost=2500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_echo_sabre', localized_name='Echo Sabre', cost=2500, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_armlet', localized_name='Armlet of Mordiggian', cost=2500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_diffusal_blade', localized_name='Diffusal Blade', cost=2500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_witch_blade', localized_name='Witch Blade', cost=2600, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_vladmir', localized_name="Vladmir's Offering", cost=2600, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_solar_crest', localized_name='Solar Crest', cost=2625, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_dagon', localized_name='Dagon', cost=2700, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_maelstrom', localized_name='Maelstrom', cost=2700, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_cyclone', localized_name="Eul's Scepter of Divinity", cost=2725, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_rod_of_atos', localized_name='Rod of Atos', cost=2750, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_eagle', localized_name='Eaglesong', cost=2800, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_reaver', localized_name='Reaver', cost=2800, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_mystic_staff', localized_name='Mystic Staff', cost=2800, secret_shop=1, recipe=0,
              parent_name=[]),
         Item(name='item_spirit_vessel', localized_name='Spirit Vessel', cost=2840, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_basher', localized_name='Skull Basher', cost=2875, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_aeon_disk', localized_name='Aeon Disk', cost=3000, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_soul_booster', localized_name='Soul Booster', cost=3000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_invis_sword', localized_name='Shadow Blade', cost=3000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_eternal_shroud', localized_name='Eternal Shroud', cost=3300, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_pipe', localized_name='Pipe of Insight', cost=3475, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_orchid', localized_name='Orchid Malevolence', cost=3475, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_desolator', localized_name='Desolator', cost=3500, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_heavens_halberd', localized_name="Heaven's Halberd", cost=3550, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_crimson_guard', localized_name='Crimson Guard', cost=3600, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_relic', localized_name='Sacred Relic', cost=3750, secret_shop=1, recipe=0, parent_name=[]),
         Item(name='item_lotus_orb', localized_name='Lotus Orb', cost=3850, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_dagon_2', localized_name='Dagon', cost=3950, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_moon_shard', localized_name='Moon Shard', cost=4000, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_black_king_bar', localized_name='Black King Bar', cost=4050, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_bfury', localized_name='Battle Fury', cost=4100, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_sange_and_yasha', localized_name='Sange and Yasha', cost=4100, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_kaya_and_sange', localized_name='Kaya and Sange', cost=4100, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_yasha_and_kaya', localized_name='Yasha and Kaya', cost=4100, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_boots_of_bearing', localized_name='Boots of Bearing', cost=4125, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_wraith_pact', localized_name='Wraith Pact', cost=4200, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_ultimate_scepter', localized_name="Aghanim's Scepter", cost=4200, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_hurricane_pike', localized_name='Hurricane Pike', cost=4450, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_travel_boots_2', localized_name='Boots of Travel 2', cost=4500, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_bloodstone', localized_name='Bloodstone', cost=4600, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_sphere', localized_name="Linken's Sphere", cost=4600, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_manta', localized_name='Manta Style', cost=4600, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_ethereal_blade', localized_name='Ethereal Blade', cost=4650, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_nullifier', localized_name='Nullifier', cost=4725, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_shivas_guard', localized_name="Shiva's Guard", cost=4850, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_monkey_king_bar', localized_name='Monkey King Bar', cost=4975, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_butterfly', localized_name='Butterfly', cost=4975, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_grandmasters_glaive', localized_name="Grandmaster's Glaive", cost=5000, secret_shop=0,
              recipe=0, parent_name=[]),
         Item(name='item_refresher', localized_name='Refresher Orb', cost=5000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_heart', localized_name='Heart of Tarrasque', cost=5000, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_radiance', localized_name='Radiance', cost=5050, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_satanic', localized_name='Satanic', cost=5050, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_guardian_greaves', localized_name='Guardian Greaves', cost=5100, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_assault', localized_name='Assault Cuirass', cost=5125, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_greater_crit', localized_name='Daedalus', cost=5150, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_dagon_3', localized_name='Dagon', cost=5200, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_octarine_core', localized_name='Octarine Core', cost=5275, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_skadi', localized_name='Eye of Skadi', cost=5300, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_silver_edge', localized_name='Silver Edge', cost=5450, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_mjollnir', localized_name='Mjollnir', cost=5600, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_sheepstick', localized_name='Scythe of Vyse', cost=5675, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_rapier', localized_name='Divine Rapier', cost=5950, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_gungir', localized_name='Gleipnir', cost=6150, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_revenants_brooch', localized_name="Revenant's Brooch", cost=6200, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_abyssal_blade', localized_name='Abyssal Blade', cost=6250, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_helm_of_the_overlord', localized_name='Helm of the Overlord', cost=6325, secret_shop=0,
              recipe=0, parent_name=[]),
         Item(name='item_dagon_4', localized_name='Dagon', cost=6450, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_overwhelming_blink', localized_name='Overwhelming Blink', cost=6800, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_swift_blink', localized_name='Swift Blink', cost=6800, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_arcane_blink', localized_name='Arcane Blink', cost=6800, secret_shop=0, recipe=0,
              parent_name=[]),
         Item(name='item_bloodthorn', localized_name='Bloodthorn', cost=6800, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_wind_waker', localized_name='Wind Waker', cost=6825, secret_shop=0, recipe=0, parent_name=[]),
         Item(name='item_dagon_5', localized_name='Dagon', cost=7700, secret_shop=0, recipe=0, parent_name=[])]
